name: Update Weather Forecast

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run script
      run: python script.py
    - name: Commit changes
      run: |
        git config --global user.email "your_email@example.com"
        git config --global user.name "Your Name"
        git add .
        git commit -m "Update weather forecast"
        git push
